#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to Oppoin's Mosquitto v2 One-Click Droplet.

To keep this Droplet secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH), 80 (HTTP), and 443 (HTTPS).

If you have questions, you can go to https://bit.ly/oppoin-image-builders-support

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
